"""Central AVISTA product identity and report attribution."""

from __future__ import annotations

from datetime import datetime

from app.__version__ import APP_NAME, __version__


APPLICATION_NAME = APP_NAME
APPLICATION_VERSION = __version__
APPLICATION_TAGLINE = (
    "Automated Vehicle Infrastructure-Sensitive Tabular Analysis"
)
DEVELOPERS = (
    "Md Monzurul Islam (Xatta Trone)",
    "Shriyank Somvanshi",
)
GITHUB_PROFILES = (
    ("Md Monzurul Islam", "https://github.com/xatta-trone"),
    ("Shriyank Somvanshi", "https://github.com/shriyanksomvanshi"),
)


def report_footer(timestamp: datetime | None = None) -> dict[str, str]:
    """Return standard attribution fields for generated reports."""

    generated_on = (timestamp or datetime.now()).isoformat(timespec="seconds")
    return {
        "generated_by": APPLICATION_NAME,
        "version": APPLICATION_VERSION,
        "generated_on": generated_on,
    }


def report_footer_text(timestamp: datetime | None = None) -> str:
    """Return the standard human-readable report footer."""

    footer = report_footer(timestamp)
    return "\n".join(
        [
            f"Generated by {footer['generated_by']}",
            f"Version {footer['version']}",
            f"Generated on {footer['generated_on']}",
        ]
    )


def about_text() -> str:
    """Return the plain-text AVISTA About content."""

    lines = [
        APPLICATION_NAME,
        f"Version {APPLICATION_VERSION}",
        "",
        APPLICATION_TAGLINE,
        "",
        "Developed by:",
        *DEVELOPERS,
        "",
        "GitHub:",
    ]
    for name, url in GITHUB_PROFILES:
        lines.extend([f"{name}:", url, ""])
    return "\n".join(lines).rstrip()
